version: 1.0.{build}

environment:
    matrix:
        - MSVC_TOOLSET: 120
          BUILD_ZLIB: 1
          BUILD_GFLAGS: 0
          BUILD_GLOG: 0
          BUILD_HDF5: 1
          BUILD_BOOST: 0
          BUILD_LEVELDB: 0
          BUILD_LMDB: 0
          BUILD_OPENCV: 1
          BUILD_PROTOBUF: 0
          BUILD_OPENBLAS: 0
          BUILD_SNAPPY: 0

        - MSVC_TOOLSET: 120
          BUILD_ZLIB: 1
          BUILD_GFLAGS: 0
          BUILD_GLOG: 0
          BUILD_HDF5: 0
          BUILD_BOOST: 1
          BUILD_LEVELDB: 1
          BUILD_LMDB: 0
          BUILD_OPENCV: 0
          BUILD_PROTOBUF: 0
          BUILD_OPENBLAS: 0
          BUILD_SNAPPY: 0

        - MSVC_TOOLSET: 120
          BUILD_ZLIB: 0
          BUILD_GFLAGS: 1
          BUILD_GLOG: 1
          BUILD_HDF5: 0
          BUILD_BOOST: 0
          BUILD_LEVELDB: 0
          BUILD_LMDB: 0
          BUILD_OPENCV: 0
          BUILD_PROTOBUF: 0
          BUILD_OPENBLAS: 0
          BUILD_SNAPPY: 0

        - MSVC_TOOLSET: 120
          BUILD_ZLIB: 1
          BUILD_GFLAGS: 0
          BUILD_GLOG: 0
          BUILD_HDF5: 0
          BUILD_BOOST: 0
          BUILD_LEVELDB: 0
          BUILD_LMDB: 1
          BUILD_OPENCV: 0
          BUILD_PROTOBUF: 1
          BUILD_OPENBLAS: 1
          BUILD_SNAPPY: 1

        - MSVC_TOOLSET: 140
          BUILD_ZLIB: 1
          BUILD_GFLAGS: 0
          BUILD_GLOG: 0
          BUILD_HDF5: 1
          BUILD_BOOST: 0
          BUILD_LEVELDB: 0
          BUILD_LMDB: 0
          BUILD_OPENCV: 1
          BUILD_PROTOBUF: 0
          BUILD_OPENBLAS: 0
          BUILD_SNAPPY: 0

        - MSVC_TOOLSET: 140
          BUILD_ZLIB: 1
          BUILD_GFLAGS: 0
          BUILD_GLOG: 0
          BUILD_HDF5: 0
          BUILD_BOOST: 1
          BUILD_LEVELDB: 1
          BUILD_LMDB: 0
          BUILD_OPENCV: 0
          BUILD_PROTOBUF: 0
          BUILD_OPENBLAS: 0
          BUILD_SNAPPY: 0

        - MSVC_TOOLSET: 140
          BUILD_ZLIB: 0
          BUILD_GFLAGS: 1
          BUILD_GLOG: 1
          BUILD_HDF5: 0
          BUILD_BOOST: 0
          BUILD_LEVELDB: 0
          BUILD_LMDB: 0
          BUILD_OPENCV: 0
          BUILD_PROTOBUF: 0
          BUILD_OPENBLAS: 0
          BUILD_SNAPPY: 0

        - MSVC_TOOLSET: 140
          BUILD_ZLIB: 1
          BUILD_GFLAGS: 0
          BUILD_GLOG: 0
          BUILD_HDF5: 0
          BUILD_BOOST: 0
          BUILD_LEVELDB: 0
          BUILD_LMDB: 1
          BUILD_OPENCV: 0
          BUILD_PROTOBUF: 1
          BUILD_OPENBLAS: 1
          BUILD_SNAPPY: 1

build_script:
- cmd: >-
    call build_appveyor.cmd

artifacts:
- path: build\install
  name: libraries

#cache:
#- build\install\super-builder-libraries